#framework:
#    secret: '%env(APP_SECRET)%'
#    #csrf_protection: true
#    #http_method_override: true
#
#    # Enables session support. Note that the session will ONLY be started if you read or write from it.
#    # Remove or comment this section to explicitly disable session support.
#    session:
#        handler_id: null
#
#    #esi: true
#    #fragments: true
#    php_errors:
#        log: true
framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_lifetime: 0
        handler_id: null
#    router:
#        resource: "%kernel.root_dir%/config/packages/routing.yaml"
#        strict_requirements: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%env(APP_LOCALE)%"
    translator:
        fallbacks: ['en']
    trusted_hosts: ~
    trusted_proxies: ~
    fragments: ~
    translator: ~

    php_errors:
        log: true