framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_lifetime: 0
        handler_id: null
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%env(APP_LOCALE)%"
    translator:
        fallbacks: ['en']
    trusted_hosts: ~
    fragments: ~

    php_errors:
        log: true