security:
    encoders:
        App\UserBundle\Entity\User:
            algorithm: bcrypt
    providers:
        users:
            entity:
                class: App\UserBundle\Entity\User
                property: email

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            pattern: ^/
            anonymous: ~
            logout_on_user_change: true
            logout:
                path: app_user.logout
            guard:
                provider: users
                authenticators:
                    - App\UserBundle\Security\LoginFormAuthenticator
        main:
            pattern: ^/user
            logout_on_user_change: true
            anonymous: true
    access_control:
        - { path: '^/user/login$', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/user/register$', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', role: ROLE_USER }
        - { path: '^/comment/\d+$/', role: ROLE_ADMIN }