version: '3'
services:
  php:
    container_name: php_container
    image: php:7.1
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    user: ${UID}:${GID}
    depends_on:
      - mysql
    ports:
      - 9090:9000
    volumes:
      - ./:/app
      - ~/.composer/composer.json:/home/dockeruser/.composer/composer.json
      - ~/.composer/.htaccess:/home/dockeruser/.composer/.htaccess
    dns:
      - 192.168.0.254
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    container_name: nginx_container
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - 3334:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}